### ISSUE TITLE
Feedback homework week 2

### ISSUE THREAD

**Issue by remarcmij** [nour25ghazal/hyf-JavaScript3#2]
Hi نور, here is my feedback on your homework for week 2.

**1.** Your conversion from callbacks to promises is mostly right, except for catching errors in your function `contrInfo()` (which I hoped you would have renamed to `contributorsInfo()` by now, as per my previous feedback). If I force a 4xx response from GitHub for the inner `fetchJSON()` by appending a `x` to the URL, it won't be caught by the `.catch()` method:

```js
function contrInfo(data) {
  // ...
  fetchJSON(data)
    .then(data => {
      const contrUrl = data.contributors_url;
      fetchJSON(contrUrl + 'x')
        .then(contrUrl => {
          // ...
        });
    })
    .catch(error => {
      console.log(error.message);
    });
}
```

This code produces the following error message in the console:

```
app.js:15 Uncaught (in promise) Error: Not Found
    at XMLHttpRequest.xhr.onreadystatechange (app.js:15)
```

To ensure that the terminating `.catch()` also catches errors from the inner `fetchJSON()` call (`fetchJSON()` returns a promise), you must add the `return` keyword before the call to `fetchJSON()`, like this:

```js
function contrInfo(data) {
  // ...
  return fetchJSON(data)
    .then(data => {
      const contrUrl = data.contributors_url;
      fetchJSON(contrUrl + 'x')
        .then(contrUrl => {
          // ...
        });
    })
    .catch(error => {
      console.log(error.message);
    });
}
```

Now, your `.catch()` handler picks up the error and displays `Not found` in the console.

Referring to the same code snippet above, the parameter name for the arrow function of the `.then()` method should not be `contrUrl`. You should always ask yourself: _"What will the variable hold?"_. In this case, what you get back from this `fetchJSON()` call is an array of contributors information. So this parameter should be called `contributors`. The name `contrUrl` is misleading because it is not a URL.

**2.** Of course, error messages in the console will not be visible to regular users, who are not in the habit of visiting web pages with the console open. So please render your errors to the web page for week 3, as I asked in this [slack message](https://hackyourfuture.slack.com/files/U383PTTK9/FA1C6Q7L4/404.png).

**X.** Prefer `for...of` loops over (old-fashioned) `for` loops that use in index variable. For instance this code:

```js
for (let i = 0; i < data.length; i++) {
  createAndAppend('option', select, {
    html: data[i].name,
    value: data[i].url
  });
}
```

could be rewritten as:

```js
for (const repo of data) {
  createAndAppend('option', select, {
    html: repo.name,
    value: repo.url
  });
}
```

Of course, it would even be better if you renamed `data` (which is a rather meaningless name) to `repos`, because we are talking about an array of repository information here, like below: (Always seek for the most descriptive name you can think of for your variables, functions and parameters). 

```js
for (const repo of repos) {
  createAndAppend('option', select, {
    html: repo.name,
    value: repo.url
  });
}
```

Please check all of your code and confirm that the names reflect their content or function. The computer doesn't care about the names you use but we, fellow humans reading your code, do very much care.

**3.** In line 150 of your code you are still using a `for...in` loop. Please check the issue number 4 in the previous week's feedback how to correct it.

**4.** On the use of blank lines: Blank lines should be used as a separator between blocks of related code, and only for that purpose. Any blank line that does not serve that purpose should be removed. Think of blank lines as similar to paragraph separators in a book. A book with randomly placed blank lines wouldn't be a nice read. Same holds true for source code. The computer won't mind, but we, fellow human readers of your code _do_ mind.

Use one consecutive blank line to separate pieces of code; do not use multiple lines.

**5.** Finally, most JavaScript developers now prefer two spaces instead of four to indent their code. If you would like to try that, in VSCode you can do that by adding these User Settings:

```
"editor.detectIndentation": false,
"editor.tabSize": 2,
```

If you now reformat your code in VSCode it will indent with two spaces.

**Comment by nour25ghazal** [comment]
the issue is solved
